package com.acp.gui;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dewal
 */
public class OwnerAccountTool extends javax.swing.JFrame {

    /**
     * Creates new form OwnerOptionsJFrame
     */
    public OwnerAccountTool() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathJButton = new javax.swing.JButton();
        exportJButton = new javax.swing.JButton();
        lookupJButton = new javax.swing.JButton();
        loyaltyJButton = new javax.swing.JButton();
        settingsJButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pathJButton.setText("Set Export Path");
        pathJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathJButtonActionPerformed(evt);
            }
        });

        exportJButton.setText("Export Reports...");
        exportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportJButtonActionPerformed(evt);
            }
        });

        lookupJButton.setText("Account Lookup");
        lookupJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupJButtonActionPerformed(evt);
            }
        });

        loyaltyJButton.setText("Add Loyalty Points");
        loyaltyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loyaltyJButtonActionPerformed(evt);
            }
        });

        settingsJButton.setText("Settings");
        settingsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsJButtonActionPerformed(evt);
            }
        });

        pathLabel.setText("Path: C/Users/Owner/Program Files/ACP/Reports");

        ownerLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ownerLabel.setText("Owner Account Tools");

        logoutJButton.setText("Log Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pathJButton)
                    .addComponent(exportJButton)
                    .addComponent(lookupJButton)
                    .addComponent(loyaltyJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 115, Short.MAX_VALUE))
                            .addComponent(pathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exportJButton, lookupJButton, loyaltyJButton, pathJButton, settingsJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathJButton)
                    .addComponent(pathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lookupJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loyaltyJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutJButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pathJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathJButtonActionPerformed

    }//GEN-LAST:event_pathJButtonActionPerformed

    private void loyaltyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loyaltyJButtonActionPerformed
    }//GEN-LAST:event_loyaltyJButtonActionPerformed

    private void exportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportJButtonActionPerformed

    }//GEN-LAST:event_exportJButtonActionPerformed

    private void lookupJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupJButtonActionPerformed

    }//GEN-LAST:event_lookupJButtonActionPerformed

    private void settingsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsJButtonActionPerformed

    }//GEN-LAST:event_settingsJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OwnerAccountTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OwnerAccountTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OwnerAccountTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OwnerAccountTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OwnerAccountTool().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton lookupJButton;
    private javax.swing.JButton loyaltyJButton;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JButton pathJButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JButton settingsJButton;
    // End of variables declaration//GEN-END:variables


    public JButton getPathJButton() {
        return pathJButton;
    }

    public JButton getExportJButton() {
        return exportJButton;
    }

    public JButton getLookupJButton() {
        return lookupJButton;
    }

    public JButton getLoyaltyJButton() {
        return loyaltyJButton;
    }

    public JButton getSettingsJButton() {
        return settingsJButton;
    }

    public JButton getLogoutJButton() {
        return logoutJButton;
    }
    
    public void setPathLabel(String path){
        pathLabel.setText(path);
    }
}
